services:
  mysqldb:
    image: mysql:8.1-oracle
    container_name: mysql
    environment:
      - MYSQL_DATABASE=api_star_wars
      #    - MYSQL_DATABASE=${MYSQL_DATABASE}
      #    - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10


volumes:
  data:
    driver: local